---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  vars:
    _service_test_command:
      default: /usr/bin/sleep
      Alpine: /bin/sleep
      Debian: /bin/sleep
      Ubuntu-16: /bin/sleep
      Ubuntu-18: /bin/sleep
    service_test_command: "{{ _service_test_command[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_service_test_command[ansible_os_family] | default(_service_test_command['default'])) }}"  # noqa 204 Just long.

  roles:
    - role: boutetnico.influxdb
    - role: buluma.service
      service_list:
        - name: influxdb
          description: influxdb service
          start_command: "{{ service_test_command }} 3600"
          state: started
          enabled: yes
        - name: influxdb
          description: influxdb service
          start_command: "{{ service_test_command }} 3601"
          state: stopped
          enabled: no

      influxdb_orgs:
        - name: main-org
          description: Main organization
        - name: guest-org

      influxdb_users:
        - name: admin01
          org: main-org
          password: secretPassword
        - name: guest01
          org: guest-org
          password: secretPassword

      influxdb_buckets:
        - name: bucket01
          description: First bucket
          org: main-org
          retention: 1d
        - name: bucket02
          org: main-org
