---
#
# Ansible managed
#

name: Ansible Molecule

on:
  # Schedule updates (once daily)
  schedule:
    - cron: '35 18 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main", "testing"]}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "ubuntu"
            tag: "18.04"
          - image: "ubuntu"
            tag: "20.04"
          - image: "debian"
            tag: "jessie"
          - image: "debian"
            tag: "stretch"
          - image: "fedora"
            tag: "36"
          - image: "fedora"
            tag: "35"
          - image: "fedora"
            tag: "34"
          - image: "fedora"
            tag: "33"
          - image: "centos"
            tag: "centos8"
          - image: "centos"
            tag: "centos7"
          - image: "alpine"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
