---
#
# Ansible managed
#

name: Ansible Molecule

on:
  # Schedule updates (once daily)
  schedule:
    - cron: '17 9 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main", "testing"]}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          command: lint
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Remove pre-installed ansible
        run: sudo apt-get remove --purge -y ansible

      - name: Install dependencies
        run: pip install ansible ansible-lint docker flake8 molecule molecule-docker pytest-testinfra

      - name: Display versions
        run: |
          python -c "import sys; print(sys.version)"
          pip --version
          ansible --version
          molecule --version

      - name: Run Molecule
        run: molecule test --all
